import React, { useState, useEffect } from 'react';
import { Row, Col, Tabs, Typography, Form, Input, Button, DatePicker } from 'antd';
import { useParams, useHistory } from "react-router-dom";
import moment from 'moment';

const { Title } = Typography;
const dateFormat = 'YYYY/MM/DD';

const InputForm = (props) => {
    const [number, setNumber] = useState(null);
    const [date, setDate] = useState(null);
    const [dateNeeded, setDateNeeded] = useState(null);
    const [department, setDepartment] = useState(null);
    const [remarks, setRemarks] = useState(null);

    const { id } = useParams();
    const history = useHistory(); 

    useEffect(() => {
        if(typeof(id) !== 'undefined' && id != null){
            console.log("Load data for " + id)
            console.log("Set state")

            //dummy data
            setNumber(1)
        }
    });

    const onFinish = (values) => {
        console.log('Success:', values);
    };
    
    const onFinishFailed = (errorInfo) => {
        console.log('Failed:', errorInfo);
    };

    return (
        <div>
            <Row><Title level={3}>{props.title}</Title></Row>
            <Row>
                <Col span={20}>
                    <Form
                        {...styles.layout}
                        name="form"
                        onFinish={onFinish}
                        onFinishFailed={onFinishFailed}    
                    >
                        <Form.Item
                            label="PRF Number"
                            name="number"
                        >
                            <Input 
                                placeholder={number === null ? ("AUTOGENERATED UPON CREATION.") : (number)}
                                disabled={true}
                            />
                        </Form.Item>

                        <Form.Item
                            label="PRF Date"
                            name="date"
                            rules={[{ required: true }]}
                        >
                            <DatePicker defaultValue={moment()} format={dateFormat} style={styles.datePicker}/>
                        </Form.Item>

                        <Form.Item
                            label="Date Needed"
                            name="dateneeded"
                            rules={[{ required: true }]}
                        >
                        <DatePicker defaultValue={moment()} format={dateFormat}  style={styles.datePicker}/>
                        </Form.Item>

                        <Form.Item
                            label="Department"
                            name="department"
                            rules={[{ required: true }]}
                        >
                            <Input/>
                        </Form.Item>

                        <Form.Item
                            label="Remarks"
                            name="remarks"
                            rules={[{ required: true }]}
                        >
                            <Input.TextArea/>
                        </Form.Item>
                        <div style={styles.tailLayout}>
                            <Button type="primary" htmlType="submit">
                                Submit
                            </Button>
                            <Button style={{marginRight: "3%"}} onClick={() => {history.goBack()}}>
                                Cancel
                            </Button>
                        </div>

                    </Form>
                </Col>
            </Row>
        </div>
    )
}

export default InputForm

const styles = {
    layout: {
        labelCol: { 
            span: 8 
        },
        wrapperCol: { 
            span: 16 
        },
    },
    tailLayout: {
        display: "flex",
        flexDirection: "row-reverse",
        
    },
    datePicker: {
        float: "left"
    }
}